In [1]:
from scipy import sparse

train = sparse.load_npz("train.npz")
train

<14590x77888 sparse matrix of type '<class 'numpy.float64'>'
	with 2026769 stored elements in Compressed Sparse Row format>

In [3]:
from sklearn.cluster import MeanShift, estimate_bandwidth
None

In [4]:
from sklearn.datasets import make_blobs
centers = [[1, 1], [-1, -1], [1, -1]]
X, _ = make_blobs(n_samples=10000, centers=centers, cluster_std=0.6)
X

/raid/alebedev/myenvtr/lib/python3.7/site-packages/sklearn/feature_extraction/image.py:167: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int):


array([[ 2.29281997,  1.3972785 ],
       [ 0.20816955, -1.23198747],
       [ 1.29408237, -1.31014611],
       ...,
       [ 0.63941025, -0.32759279],
       [ 0.91206202, -0.83378002],
       [ 1.43976635, -1.18688578]])

In [5]:
X = train.toarray()
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [6]:
import numpy as np

In [8]:
bandwidth = estimate_bandwidth(X, quantile=0.2, n_samples=500)
ms = MeanShift(bandwidth=bandwidth, bin_seeding=True)

/raid/alebedev/myenvtr/lib/python3.7/site-packages/sklearn/neighbors/base.py:441: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  old_joblib = LooseVersion(joblib_version) < LooseVersion('0.12')
/raid/alebedev/myenvtr/lib/python3.7/site-packages/sklearn/neighbors/base.py:441: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  old_joblib = LooseVersion(joblib_version) < LooseVersion('0.12')


In [9]:
ms.fit(X)

/raid/alebedev/myenvtr/lib/python3.7/site-packages/sklearn/neighbors/base.py:737: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(joblib_version) < LooseVersion('0.12'):
/raid/alebedev/myenvtr/lib/python3.7/site-packages/sklearn/neighbors/base.py:737: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(joblib_version) < LooseVersion('0.12'):
/raid/alebedev/myenvtr/lib/python3.7/site-packages/sklearn/neighbors/base.py:737: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(joblib_version) < LooseVersion('0.12'):
/raid/alebedev/myenvtr/lib/python3.7/site-packages/sklearn/neighbors/base.py:737: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(joblib_version) < LooseVersion('0.12'):
/raid/alebedev/myenvtr/lib/python3.7/site-packages/sklearn/neighbors

MeanShift(bandwidth=1.399516124901622, bin_seeding=True, cluster_all=True,
          min_bin_freq=1, n_jobs=None, seeds=None)

In [10]:
cluster_labels = ms.labels_
cluster_labels

array([0, 0, 0, ..., 0, 0, 0])

In [14]:
cluster_labels.sum()

0

In [11]:
n_clusters_ = len(np.unique(cluster_labels))

print("Количество кластеров: ", n_clusters_)

Количество кластеров:  1


In [12]:
submission = np.arange(len(cluster_labels)).reshape(-1, 1)
submission = np.concatenate((submission, cluster_labels.reshape(-1, 1)), axis=1)

In [13]:
np.savetxt("submission_meanshift.csv", submission, delimiter=",", header="ID,TARGET", comments="", fmt='%d')